### PR TITLE
Don't cache large matrix objects

### PR DESCRIPTION
**Pull request by eriknw**
If we cached `AT`, `offdiag`, `U+`, `U-`, `L+`, and `L-`, we could use 4x more memory than `A`. I don't know if this is worth it.

Should we add a config to allow this to be enabled/disabled?

### CODE REVIEW

**Comment by SultanOrazbayev** [comment]
Is it challenging to setup some sort of `views` on `A`? (I'm not sure how feasible it is.)

**Comment by eriknw** [comment]
> Is it challenging to setup some sort of views on A? (I'm not sure how feasible it is.)

What do you mean by `view`?  I think the C++ graphblas spec may have something like this.

I think my ideal solution would be to have a configuration for how large the cache for each graph can get (such as 2.1x the matrix `A`), and to employ e.g. an LRU cache or similar (we may weigh based on expected usage, such as try to keep `AT`) to choose what to discard. That way, a couple large matrices such as `AT` and `L+` could be available in case the user makes heavy use of them. Right now, it's unclear how often these large matrices may be used--we need to write more algorithms!

**Comment by SultanOrazbayev** [comment]
I had in mind the zero-copy `view` as in numpy, re: https://numpy.org/doc/stable/user/basics.copies.html

**Comment by eriknw** [comment]
I see, thanks. Right, I don't think that would be very easy (but would be a great solution if we could do it!).

**Comment by eriknw** [comment]
Closing. Caching can be nice, and I think these do get used. I think we ought to pursue a different strategy--perhaps expose the cache to the user or add configuration.

**Pull request closed without merging**
